baseURL = "https://makeroni.cc"
languageCode = "en-gb"
title = "Makeroni"
#theme = ["osm","ananke"]
SectionPagesMenu = "main"
DefaultContentLanguage = "en"
enableRobotsTXT = true
theme = [ "github.com/theNewDynamic/gohugo-theme-ananke/v2" , "github.com/Hanzei/hugo-component-osm" ]

[pagination]
  pagerSize=10

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  site_logo = "/images/white-small-site-logo-64.png"
  show_reading_time = true
  description = "A place to meet and make online (and physically)"
  mainSections= [ "news","projects","reviews" ]
  favicon = "makeroni-white-small-logo-favicon.png"
  # this is used for the OpenGraph Card image if no featured image per page, must be min 120x120
  images = [ "makeroni-white-small-logo-favicon.png" ]
  body_classes= "avenir bg-near-white"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/spencer-lbqLxgvLt0U-unsplash.jpg"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/makeronicc"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/makeronicc"

[[params.ananke_socials]]
name = "mastodon"
url = "https://mastodon.org.uk/@makeroni"

[[params.ananke_socials]]
name = "discord"
url = "https://discord.gg/HYYXHSu"
